### ISSUE TITLE
import SvgIconComponent documentation 

### ISSUE THREAD

**Issue by Jobu08** [ngneat/svg-icon#115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Since upgrade to version 5, library is provided as Standalone app. It would be fine to mention in readme that user needs to import SvgIconComponent in order to use it.

**Comment by NetanelBasal** [comment]
![IMG_20221202_120556.jpg](https://user-images.githubusercontent.com/6745730/205268182-b846a1b0-482c-48f6-8759-7b81d6fb2c92.jpg)

**Comment by Jobu08** [comment]
I've overlooked it. But consider adding it to code examples for modules in [Register icons locally](https://github.com/ngneat/svg-icon#register-icons-locally) or  [Icons rendering](https://github.com/ngneat/svg-icon#icons-rendering). 

Closing the issue
