### ISSUE TITLE
Icon provided at standalone component level is not rendering

### ISSUE THREAD

**Issue by jsgopher** [ngneat/svg-icon#132]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Icon provided at standalone component level is not rendering.

## Expected behavior

Should render all the provided icons at root level and component level.

## Minimal reproduction of the problem with instructions

Issue is reproduced in this [stackblitz](https://stackblitz.com/edit/angular-jyazg2?file=src%2Fmain.ts)

![image](https://user-images.githubusercontent.com/105229673/235646802-f63c8384-009b-4a29-8352-373cadf06e1b.png)

## Environment

<pre><code>
Angular version: 15.2.8

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Stackblitz

Others:

</code></pre>

Below is the list of dependencies

![image](https://user-images.githubusercontent.com/105229673/235647156-56cdba5f-99ea-4005-a747-1e2504060c8a.png)

**Comment by NetanelBasal** [comment]
It can't be done.

**Comment by NetanelBasal** [comment]
I've added a protection in the new version
