### ISSUE TITLE
Can't resolve '../assets/svg/svg-icons'

### ISSUE THREAD

**Issue by RonnieRocket147** [ngneat/svg-icon#15]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When following the instructions to install the package the following error occurs:

```
Failed to compile.

./src/app/app.module.ts
Module not found: Error: Can't resolve '../assets/svg/svg-icons' in '/Users/xyz/Projects/dashboard/src/app'

```
## Expected behavior

The svg-icons file should be in the mentioned location.

## Minimal reproduction of the problem with instructions

Simply run `ng add @ngneat/svg-icon`

## Environment

<pre><code>
Angular version: 11.0.5

Browser:
- [X] Chrome (desktop) version 87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.19.0  
- Platform:  Mac

Others:

The following files are generated. As you can see the referenced file is not there:

app/index.ts
app/svg/app-*.icon.ts (all icon files)
app/svg/my-icons.model.ts

</code></pre>

**Comment by RonnieRocket147** [comment]
```
    /       |\   \  /   / /  _____|       |           | /  __  \         |           |   /       |
   |   (----` \   \/   / |  |  __   ______`---|  |----`|  |  |  |  ______`---|  |----`  |   (----`
    \   \      \      /  |  | |_ | |______|   |  |     |  |  |  | |______|   |  |        \   \    
.----)   |      \    /   |  |__| |            |  |     |  `--'  |            |  |    .----)   |   
|_______/        \__/     \______|            |__|      \______/             |__|    |_______/    

svg-to-ts:  ℹ️ Configuration found under: /Users/mlindenbergh/xyz/dashboard/package.json
svg-to-ts:  ℹ️ No typeName provided, "myIcons" will be used
svg-to-ts:  ℹ️ No generateTypeObject provided, "false" will be used
svg-to-ts:  ℹ️ No interfaceName provided, "MyIcon" will be used
svg-to-ts:  ℹ️ No modelFileName provided, "my-icons.model" will be used
svg-to-ts:  ℹ️ No preCompileSources flag provided, "false" will be used
svg-to-ts:  ℹ️ No preCompileSources flag provided, "false" will be used
svg-to-ts:  ℹ️ No preCompileSources flag provided, "index" will be used
svg-to-ts:  ℹ️ We are using the conversiontype "files"
svg-to-ts:  ℹ️ deleting output directory: ./src/app/svg
svg-to-ts:  -----------------------File optimization----------------------
svg-to-ts:  ℹ️ optimize svg: test.svg
svg-to-ts:  ℹ️ write file svg: ./src/app/svg/app-test.icon.ts
svg-to-ts:  ----------------------------------------------------------------
svg-to-ts:  ℹ️ write index.ts
svg-to-ts:  ℹ️ model-file successfully generated under ./src/app/svg/my-icons.model.ts
svg-to-ts:  ========================================================
svg-to-ts:  your files were successfully created under: ./src/app
svg-to-ts:  don't forget to copy this folder to your dist in a post build script - enjoy your tree-shakable icon library 😎
svg-to-ts:  ========================================================

```

**Comment by NetanelBasal** [comment]
It seems like you don't have SVG files in this location. You're responsible for the `srcFiles` path.

**Comment by RonnieRocket147** [comment]
I have 42 SVG files which were all correctly converted. I simplified the above output which shows only 1 icon:

```
svg-to-ts:  ℹ️ optimize svg: test.svg
svg-to-ts:  ℹ️ write file svg: ./src/app/svg/app-test.icon.ts

```

**Comment by RonnieRocket147** [comment]
I resolved this by creating the missing file myself.

**Comment by erhise** [comment]
I had the same problem, the svg-icons file was never created
