### ISSUE TITLE
Icon is not rendered with IE11

### ISSUE THREAD

**Issue by RonnieRocket147** [ngneat/svg-icon#16]
_Originally posted by @RonnieRocket147 in https://github.com/ngneat/svg-icon/issues/6#issuecomment-751733413_

The SVG icons are not displayed in IE11 although the `browserlistrc` and `polyfills.ts` are correctly configured. The console shows the error `TypeError: Argument not optional` and the `svg-icon` element has no child elements when viewed in the inspector.

What can be done to make it work in IE11?

Many thanks.

**Comment by NetanelBasal** [comment]
We work with IE, and it works. Can you try to debug it and share your findings, please?

**Comment by RonnieRocket147** [comment]
Ok thanks for this info which sounds very promising. I'll do my best to debug. Any pointers to do this are appreciated.

**Comment by RonnieRocket147** [comment]
Could it be related to this? https://stackoverflow.com/questions/41831355/svg-not-rendering-ie-11

It mentions that IE11 needs certain SVG properties which might be removed by `svg-to-ts`?

**Comment by RonnieRocket147** [comment]
The error is triggered in this piece of code:

`{key:"render",value:function(){this.key&&this.registry.hasSvg(this.key)?(this.element.classList.remove(),this.element.classList.add("svg-icon-"+this.key),this.element.innerHTML=this.registry.get(this.key)):Object(a.U)()&&console.warn(this.key+" is missing!")}}
`

`this.element.classList.remove()` needs an argument according to IE11 but is not provided. Is this a problem with the installed polyfill perhaps?

**Comment by RonnieRocket147** [comment]
`npm install --save classlist.js` is definitely **not** working.

What does work is installing the following package:

```
/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'eligrey-classlist.js';  // Run `npm install --save eligrey-classlist.js`.

```
