### ISSUE TITLE
Size not respected when [key] input changes

### ISSUE THREAD

**Issue by RonnieRocket147** [ngneat/svg-icon#17]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a detail component which displays an `svg-icon`:

`<svg-icon color="white" size="lg" [key]="getKey()"></svg-icon>`

The initial size of the icon is indeed large (48px):

`<svg-icon _ngcontent-vst-c67="" color="white" size="lg" _nghost-vst-c18="" ng-reflect-color="white" ng-reflect-size="lg" ng-reflect-key="first" role="img" class="svg-icon-first" style="color: white; font-size: 48px;">`

When the single `@Input` of the component changes the key is updated according. The icon changes correctly but the size is reverted to the default size of medium (20px) instead of the specified size of large due to the `style` attribute having the incorrect font-size:

`<svg-icon _ngcontent-vst-c67="" color="white" size="lg" _nghost-vst-c18="" ng-reflect-color="white" ng-reflect-size="lg" ng-reflect-key="second" role="img" class="svg-icon-second" style="color: white; font-size: 20px;">`

## Expected behavior

The size should remain large.

## Minimal reproduction of the problem with instructions

Create a component with an @Input that changes the svg-icon's key input.

## Environment

<pre><code>
Angular version: 11.0.5

Browser:
- [X] Chrome (desktop) version 87.0.4280.88
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by NetanelBasal** [comment]
Do you want to create a PR? The issue is [here](https://github.com/ngneat/svg-icon/blob/master/projects/ngneat/svg-icon/src/lib/svg-icon.component.ts#L79)

**Comment by RonnieRocket147** [comment]
Unfortunately I am too inexperienced to do this, however I can suggest the code change:

```
private fz: string **= null**;

...

if (changes.fontSize?.currentValue) {
  resolveFontSize = changes.fontSize.currentValue;
} else if (changes.size?.currentValue) {
  const size = changes.size.currentValue;
  resolveFontSize = this.mergedConfig.sizes[size];
**} else if (this.fz !== null) {
  resolveFontSize = this.fz;**
} else {
  const size = this.mergedConfig.defaultSize;
  if (size) {
    resolveFontSize = this.mergedConfig.sizes[size];
  }
}

```

**Comment by NetanelBasal** [comment]
I just tested it and it works fine. 

![image](https://user-images.githubusercontent.com/6745730/103405457-e328a480-4b5f-11eb-8972-fa14f37e74b0.png)

**Comment by NetanelBasal** [comment]
Try to reproduce it on stackblitz, please.

**Comment by RonnieRocket147** [comment]
https://stackblitz.com/edit/angular-jqiivv?file=src/app/app.component.ts

**Comment by NetanelBasal** [comment]
Ok so that was the case on my side: https://stackblitz.com/edit/angular-ylikhn?file=src%2Fapp%2Fapp.module.ts

That's why it important to reproduce :)

**Comment by RonnieRocket147** [comment]
You forgot to define the default `md` size in the config. Then it will not change back to the default size indeed.

**Comment by NetanelBasal** [comment]
Try 2.1.1

**Comment by RonnieRocket147** [comment]
It works 2 times now, but then it fails again. See my stackblitz.

**Comment by RonnieRocket147** [comment]
`resolveFontSize` will be set to undefined after the first change. Then the next change it will revert back to default size. I guess my proposed fix will work.

**Comment by NetanelBasal** [comment]
Sorry, I'm not in focus. Try 2.1.2

**Comment by RonnieRocket147** [comment]
And fixed 😃 Thanks for your help and happy 2021!
