### ISSUE TITLE
Support of non-square svg's

### ISSUE THREAD

**Issue by JoA-MoS** [ngneat/svg-icon#19]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Icons must have the same height and width. I would like the ability to support non square icons by adding a property to overwrite the existing functionality setting height and weight to be 1em, with the values from the input properties

## What is the motivation / use case for changing the behavior?

In our set of icons we have a few that are not square and would be nice to be able to use this library. I am willing to submit a PR if this is something you would be  interested in including in your package. I am also open to other suggested solutions.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR and add support for width and height.

**Comment by NetanelBasal** [comment]
Added in v3

**Comment by JoA-MoS** [comment]
Thank you! @NetanelBasal - I did pull the repo and couldn't get the commands in the contributing guide to run successfully so I moved on, if you think they are correct I will try again and raise an issue for clarification with the errors I saw.
