### ISSUE TITLE
ng-add svg-icons file not exists

### ISSUE THREAD

**Issue by vltansky** [ngneat/svg-icon#23]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
ng-add adds 
```js
import icons from '../assets/svg/svg-icons';
```
to `app.module.ts`, but this `assets/svg/svg-icons` not exists.
What this file supposed to be?

According to [README manual steps](https://github.com/ngneat/svg-icon#icons-rendering) looks like I need to import each icon?

```js

import { appSettings } from '../svg/app-settings.icon';

@NgModule({
  imports: [
    SvgIconsModule.forRoot({
      icons: [appSettings]
    })
...
```

**Comment by NetanelBasal** [comment]
We need to update the README. I've created our own tool to extract the SVGs.

**Comment by NetanelBasal** [comment]
It'll be great if you can do it. https://github.com/ngneat/svg-icon/tree/master/svg-generator%20

**Comment by vltansky** [comment]
I just wanted to update issue. I figured it out.
If there is no svg or only one svg in the folder - it won't create `svg-icon.ts` in the assets folder

**Comment by vltansky** [comment]
> It'll be great if you can do it. https://github.com/ngneat/svg-icon/tree/master/svg-generator%20

Ok.
BTW there is something wrong with this folder.
When tried to git clone on windows getting a lot of errors 
```
> git checkout -q --track origin/ng-add-folder
error: invalid path 'svg-generator /.gitignore'
error: invalid path 'svg-generator /.npmignore'
error: invalid path 'svg-generator /ast.ts'
error: invalid path 'svg-generator /generator.ts'
error: invalid path 'svg-generator /index.ts'
error: invalid path 'svg-generator /package-lock.json'
error: invalid path 'svg-generator /package.json'
error: invalid path 'svg-generator /tsconfig.json'
error: invalid path 'svg-generator /types.ts'
error: invalid path 'svg-generator /webpack-plugin.ts'
```

**Comment by vltansky** [comment]
@NetanelBasal are you sure it's just a readme update? Seems to me svg-icon isn't using `svg-generator` at all, but `svg-to-ts`

**Comment by NetanelBasal** [comment]
Yes, that's what I said. I've created our own SVG generator. It also exposes a Wepback plugin.

**Comment by NetanelBasal** [comment]
We should remove the svg-to-ts, and update the README so that people will use it instead
