### ISSUE TITLE
icon is missing when used in nested modules

### ISSUE THREAD

**Issue by erhise** [ngneat/svg-icon#29]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If I register an icon within a nested child module using `SvgIconsModule.forChild([...])` result will be "missing icon"

## Expected behavior

forChild method to work within nearest hierarchy? I expect the icon to be shown but are more interested in an explanation to why this is happening

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ng-neat-usage-example?file=src/app/app.component.html

## Environment

<pre><code>
Angular version: 11.0.8

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It will work ONLY on lazy loaded modules.

**Comment by erhise** [comment]
Okey, big thanks to explanation. Then I can understand why
