### ISSUE TITLE
ERROR in Symbol SvgIconComponent

### ISSUE THREAD

**Issue by Nadav-Revuze** [ngneat/svg-icon#3]
ERROR in Symbol SvgIconComponent declared in C:/.../node_modules/@ngneat/svg-icon/lib/svg-icon.component.d.ts is not exported from @ngneat/svg-icon/lib/svg-icons.module

**core module:**
```
imports:[
  ...
  SvgIconsModule.forRoot({
      icons
    }),
  ...
],
exports:[
  ...
  SvgIconsModule,
  ...
]
```

**Comment by NetanelBasal** [comment]
Is it still an issue?

**Comment by Nadav-Revuze** [comment]
yes

**Comment by NetanelBasal** [comment]
Are you importing it from `@ngneat/svg-icon`?

**Comment by Nadav-Revuze** [comment]
yes

**Comment by NetanelBasal** [comment]
Try the latest version
