### ISSUE TITLE
Support ARIA attributes on SVGs

### ISSUE THREAD

**Issue by fynnfeldpausch** [ngneat/svg-icon#30]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I did not find a way to set ARIA attributes like `aria-hidden` or `aria-label` on the SVG element.

## Expected behavior

I am able to set those attributes via the directive. Best would be to set `aria-hidden` by default and remove it if a label is supplied via an input. This is also the default behavior of Angular Material. 

## What is the motivation / use case for changing the behavior?

This would greatly help us improve the accessibility of our site.

## Environment

<pre><code>
Angular version: 11.1.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by fynnfeldpausch** [comment]
Will do as soon as I find the time this week. 👍

**Comment by NetanelBasal** [comment]
Released in v3.1.0

**Comment by fynnfeldpausch** [comment]
Sry, didn't find the time during the week.
