### ISSUE TITLE
Regression: Not possible to provide array of source paths for icon generation

### ISSUE THREAD

**Issue by criskrzysiu** [ngneat/svg-icon#36]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

You are not allowed to provide an array of source paths for icon generation, it was possible before your own svg-generator.

## Expected behavior

You can provide an array of source paths for icons.

## Minimal repoduction

old:
```json
"svg-to-ts": {
    "conversionType": "object",
    "srcFiles": [   
      "./src/assets/svg/*.svg" ,
     "./node_modules/some_lib/assets/svg/*.svg"
    ],
    "outputDirectory": "./src/assets/svg",
    "fileName": "svg-icons",
    "svgoConfig": {
      "plugins": [
        {
          "removeDimensions": true,
          "cleanupAttrs": true
        }
      ]
    }
  }
```

new:

```json
"svgGenerator": {
    "outputPath": "./src/app/svg",
    "prefix": "app",
    "srcPath": "./src/assets/svg", // Array will throw error
    "svgoConfig": {
      "plugins": [
        {
          "removeDimensions": true,
          "cleanupAttrs": true
        }
      ]
    }
  }
```

## What is the motivation/use case for changing the behavior?

For example generation of icons from node_modules **and** project assets.

## Environment

**Comment by NetanelBasal** [comment]
You can use svg-to-ts.
