### ISSUE TITLE
Error on ngAdd: Could not find file for path: /src/@app/app.module.ts

### ISSUE THREAD

**Issue by RoboZoom** [ngneat/svg-icon#38]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

On ngAdd, after the step 'update.package.json', the schematic stops with the error message: `Could not find file for path: /src/@app/app.module.ts`

## Expected behavior

Schematic effectively installs packege

## Minimal reproduction of the problem with instructions

I suspect that this issue has something to do with my application setup, though what the problem is I can't figure out.  I have a fairly normal setup Project > src > app > app.module.  The inclusion of the '@' symbol in the error seems to indicate some bug in defining a path to the app.module file. 

## What is the motivation / use case for changing the behavior?

Enabling install in all environments

## Environment

MacOS + Windows (tried both), terminal/power shell.

<pre><code>
Angular version: 11.2.2

For Tooling issues:
- Node version: v12.14.0
- Platform:  Mac/Windows

</code></pre>

**Comment by NetanelBasal** [comment]
Can you reproduce it, please?

**Comment by RoboZoom** [comment]
Yes - I'll get you a repo this week to look at.
