### ISSUE TITLE
Error: inject() must be called from an injection context (SvgIconRegistry issue)

### ISSUE THREAD

**Issue by denysSlobodianykAVA** [ngneat/svg-icon#39]
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Support request
</code></pre>

## Current behavior
Updated version to 3.1.1 (from 1.0.0) and got next error:
![Screenshot 2021-04-26 at 21 44 08](https://user-images.githubusercontent.com/72737755/116135333-addd2f00-a6d9-11eb-8f6e-6f5d6cb54fb3.png)

AppModule
```
....
imports: [
    SvgIconsModule.forRoot({ icons: ICONS }), 
    // ICONS = [ {name: 'test', data: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"></svg>' } ] 
],
providers: [
 SvgIconRegistry
// Also tried { provide: SvgIconRegistry, useClass: SvgIconRegistry }
]
...
```
Just attached like this. And got an error.
This occurs in that place: 
(ngneat-svg-icon.js:16)
```
...
class SvgIconRegistry {
    constructor(config) {
        this.svgMap = new Map();
        this.document = inject(DOCUMENT); // here, issue with 'inject'
        if (config.icons) {
            this.register(config.icons);
        }
    }
    ....
```

Also, use it inside the shared module:
```
...
imports: [
SvgIconsModule.forChild(getIcons())
],
exports: [
SvgIconsModule
]
...
```
But even when removed from the shared module - still an error.

## Expected behavior
- All works as before. The project starts without that issue.

## Minimal reproduction of the problem with instructions
- Update version from 1.0.0 into 3.1.1.
- npm run start

## What is the motivation/use case for changing the behavior?
- Can't work with the latest version of the library.

## Environment
- VS Code
<pre><code>
Angular version: 8.2.14

Browser:
- Chrome (desktop) version Version 90.0.4430.85 (Official Build) (arm64)
 
For Tooling issues:
- Node version: v14.16.0
- Platform: Mac

Other:
- I don't use Ivy
</code></pre>

**Comment by NetanelBasal** [comment]
Can you reproduce it on stackblitz, please?

**Comment by denysSlobodianykAVA** [comment]
@NetanelBasal 
yes.
https://stackblitz.com/edit/angular-ivy-d2mmak?file=src/app/app.module.ts

https://angular-ivy-d2mmak.stackblitz.io/ (inside console I got error)

**Comment by denysSlobodianykAVA** [comment]
@NetanelBasal 
Hi. Thanks for the fix.
I see that version of the library wasn't changed. After 'npm i' v3.1.1 this issue still exists.
So, need to wait for the new version with that fix?

**Comment by NetanelBasal** [comment]
3.2.0
