### ISSUE TITLE
Don't see icons, when run with aot: true (or build --prod --aot="true")

### ISSUE THREAD

**Issue by denysSlobodianykAVA** [ngneat/svg-icon#49]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request
</code></pre>

## Current behavior

No icons inside <svg-icon></svg-icon> in production build

## Expected behavior

Icons exist inside <svg-icon></svg-icon> in production build

## Minimal reproduction of the problem with instructions
- Install Angular 8.2.14, ngneat svg-icon 3.2.0.
- run locally with aot: true (inside angular.json: architect -> build -> options -> aot: true) , or build --prod --aot="true")
- when aot=true - no icon
<img width="108" alt="aotTrue-no-icon" src="https://user-images.githubusercontent.com/72737755/119642590-8b971800-be23-11eb-8b7e-5b51370f51f0.png">
<img width="585" alt="aotFalse_noIcon_code" src="https://user-images.githubusercontent.com/72737755/119643099-0c561400-be24-11eb-9d9e-1dfcc2f5e985.png">

- when aot=false - icon exist
<img width="107" alt="aotFalse-icon-exist" src="https://user-images.githubusercontent.com/72737755/119642587-8a65eb00-be23-11eb-8bb1-8c5b4320d1f8.png">

Tried to reproduce the code in stackblitz. But here somehow it works ( 
https://stackblitz.com/edit/angular-ivy-d2mmak?file=src%2Fapp%2Fapp.component.html

## What is the motivation / use case for changing the behavior?
Fix issues with build.

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [ ] Chrome (desktop) version 91.0.4472.77 (Official Build) (arm64)
 - [] Firefox 88.0.1 (64-bit)
 
For Tooling issues:
- Node version: v14.16.0
- Platform:  Mac, M1

Others:
"@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
</code></pre>

**Comment by NetanelBasal** [comment]
It works fine for me. If you still have an issue, feel free to reopen it.

**Comment by denysSlobodianykAVA** [comment]
@NetanelBasal hi, yes it still doesn't work for me (in - - prod build) . Smth went strange.
Can it be, because of Angular 8 and not using Ivy?

**Comment by NetanelBasal** [comment]
Sounds weird. Why you're still on v8?

**Comment by denysSlobodianykAVA** [comment]
Yea, I know). I am using 'set' on ContentChildren <Directive>, and it does not work fine on Angular 9, if I am changing count of templates with this directive in runtime. That is why). But someday soon I will update ng and hope will not have issue with icons
