### ISSUE TITLE
Optimize is not a function

### ISSUE THREAD

**Issue by christopher-harris** [ngneat/svg-icon#80]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running through the installation and setup instructions in the Readme and keep running into an error when running the `npm run generate-icons` script. Here is the error:

/node_modules/@ngneat/svg-generator/tree.js:49
                    svgContent: (0, svgo_1.optimize)(svgContent, { plugins, path: svgPath }).data,
                                                    ^

TypeError: (0 , svgo_1.optimize) is not a function

## Expected behavior

Expected this to work and actually generate the svg ts files.

## Minimal reproduction of the problem with instructions

Created a fresh vanilla Angular application and then ran the `ng add @ngneat/svg-icon`. New scripts were added in `package.json`. Double checked against the documentation to make sure they were correct. Ran `npm run generate-icons` and get the error.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JrPribs** [comment]
@christopher-harris was just having this issue. try installing the latest svg-generator, I installed it both globally and normally not sure which one did it I assume the global install, I'd say try normal install see if that fixes f not global should do it. @NetanelBasal can confirm possibly?

`npm i @ngneat/svg-generator@latest`
and/or
`npm i -G @ngneat/svg-generator@latest`

I think this may be missing from the ng add script or maybe just should be added to the readme

**Comment by NetanelBasal** [comment]
Yes, seems like you're using an old version of svgo.

**Comment by christopher-harris** [comment]
@JrPribs that seems to have worked...thank you.
