### ISSUE TITLE
conversionType: "object" option does not work anymore in new library version (2.0.0)

### ISSUE THREAD

**Issue by pacoita** [ngneat/svg-icon#9]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In my projects I am importing the images as an object with the following config as it is in [this article](https://netbasal.com/elegantly-manage-svg-icons-in-angular-applications-5adde68a5c46) and in the previous docs:

```
"svg-to-ts": {
    "conversionType": "object",
    "srcFiles": [
      "libs/shared/icons-lib/src/lib/icons/*.svg"
    ],
    "outputDirectory": "libs/shared/icons-lib/src/lib",
    "fileName": "svg-icons",
    "svgoConfig": {
      "plugins": [
        {
          "removeDimensions": true,
          "cleanupAttrs": true
        }
      ]
    }
  }
```

This generates the following `svg-icons.ts` file: 

```
/* 🤖 this file was generated by svg-to-ts*/
export default {
  checkmark:
    '<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path fill-rule="evenodd" clip-rule="evenodd" d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4 4 12.954 4 24s8.954 20 20 20zm-1.895-11.667c-.505 0-.992-.234-1.31-.631l-4.788-6.025c-.56-.703-.411-1.695.318-2.236a1.688 1.688 0 012.32.306l3.347 4.24c2.133-3.14 6.453-9.272 9.202-11.87a1.715 1.715 0 012.338.019 1.57 1.57 0 01-.018 2.254c-3.442 3.247-9.95 13.114-10.025 13.204-.28.433-.786.721-1.328.74h-.056z"/></svg>',
  done:
    '<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24"><path d="M0 0h24v24H0z" fill="none"/><path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"/></svg>'
```

However I then have issues while registering the SVGIconsModule, since the expected icons type is `SvgIconType | SvgIconType[]` and this brings a breaking change in my current projects:

```
import { SvgIconsModule } from '@ngneat/svg-icon';
import * as icons from './svg-icons';

@NgModule({
  imports: [
    CommonModule,
    TranslateModule,
    SvgIconsModule.forRoot({
        icons
    })]
})
```

As a different type is expected:  
```
Type 'typeof import("/Users/.../libs/shared/icons-lib/src/lib/svg-icons")' is not assignable to type 'SvgIconType | SvgIconType[] | undefined'.
```

## Expected behavior

I would like to be able to keep using `    "conversionType": "object",` as until version 1.0.3

## Minimal reproduction of the problem with instructions

Create a brand new Angular project with at least one svg icon and set the config as described above, using     "conversionType": "object"

## What is the motivation / use case for changing the behavior?

It seems to be a breaking change compared to the previous version.

## Environment

<pre><code>
Angular version: 11.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [X] Chrome (iOS) version 86.0.4240.183 
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.18.2
- Platform:  Mac

**Comment by NetanelBasal** [comment]
We released version 2, and we focused more on lazy load icons in this version. You can continue to use v1 without any worries.

**Comment by NetanelBasal** [comment]
If you want to use version 2, you can change the `conversionType` to `constants` or `files`

**Comment by pacoita** [comment]
What would be the best approach in case of a NX worspace with multiple apps that share on average 20-30 icons, plus some further one specific to each project.

In order to use the lazy load feature, we could import all common icons in a shared module and then the specific ones individually. Would this be the right approach in order to repeat importing the same common icons in every app or would you suggest a better way?

**Comment by NetanelBasal** [comment]
Sounds good
