### ISSUE TITLE
Let us define our own preserveAspectRatio for SVGs

### ISSUE THREAD

**Issue by jep-a** [ngneat/svg-icon#97]
## I'm submitting a...

Feature Request

## Current behavior

The preserveAspectRatio attribute of all SVGs are always overriden to be `xMidYMid meet` in [registry.ts#L45](https://github.com/ngneat/svg-icon/blob/1cbaf5fe8979a0b912eb9561592370bd5f2edbd3/projects/ngneat/svg-icon/src/lib/registry.ts#L45)

## Expected behavior/Proposed solution

An input on the component to set this attribute would be nice. It could also default to that value this library sets it to so there's no breaking changes.

## Minimal reproduction of the problem with instructions

Generate an SVG with a preserveAspectRatio value that is not `xMidYMid meet` and it will always be set to `xMidYMid meet`

## What is the motivation / use case for changing the behavior?

I'd like to output an SVG with a custom preserveAspectRatio to render it/align it differently but cannot

**Comment by NetanelBasal** [comment]
You're welcome to create a PR

**Comment by NetanelBasal** [comment]
Added in v5
