### ISSUE TITLE
[Feature Request] Generate standalone IconComponent per icon type

### ISSUE THREAD

**Issue by Lonli-Lokli** [ngneat/svg-icon#98]
<!-

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

One single IconComponent with support for icon types

## Expected behavior

Multiple IconComponents, declared as standalone. They will not have input iconType, but will directly use SVG.
As they will be declared as standalone, it will be a tree shakable solution as well

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by Lonli-Lokli** [comment]
How do you think should look like original icon, as a handlebar template?

**Comment by NetanelBasal** [comment]
The issue with your suggestion in general is that it will increase the bundle code size because we generate additional components.

**Comment by NetanelBasal** [comment]
In the current implementation we support tree-shaking, so what's the benefit of your suggestion?

**Comment by Lonli-Lokli** [comment]
It allows usage of specific icons - instead of specifying key='leftArrow' we can use LeftArrowIcon, without any registry.

Also it will be safer, now key of svg-icon is string, not the actual icon type

**Comment by NetanelBasal** [comment]
I understand this, but on the other side, it will increase your bundle size. I don't mind leaving this decision to the consumer.
